services:
  db-devgear:
    image: mysql:8.0
    container_name: mysql-devgear
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productos_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-productos:
    build: .
    container_name: devgear-ms-productos-1
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db-devgear
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-devgear:3306/productos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db_data:
