spring:
  application:
    name: ms-productos
  datasource:
    url: jdbc:mysql://localhost:3306/devgear_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/e5372bf0-c5e3-4286-887c-79069f209c1f/v2.0
          audiences: api://9182d5b6-da2c-4b41-849b-9887785e3cf0

server:
  port: 8081